version: '3.7'
services:
  db:
    image: postgres:15
    container_name: rates_db
    env_file:
      - .env
    ports:
      - 5432:5432

  booking:
    image: rates_image
    build:
      context: .
    container_name: rates_app
    env_file:
      - .env
    depends_on:
      - db
    command: ['/rates/entrypoint.sh']
    ports:
      - 7777:8000

volumes:
  postgresdata: